apiVersion: 1

datasources:
  - name: PostgreSQL Production Dashboard
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: production_dashboard
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
