// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203131222_UpdateUserIdAndPasswordLength")]
    partial class UpdateUserIdAndPasswordLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Equipment_Tag", b =>
                {
                    b.Property<int>("equipment")
                        .HasColumnType("integer");

                    b.Property<int>("tag_name")
                        .HasColumnType("integer");

                    b.HasKey("equipment", "tag_name");

                    b.HasIndex("tag_name");

                    b.ToTable("Equipment_Tag", (string)null);
                });

            modelBuilder.Entity("server.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Equipments", (string)null);
                });

            modelBuilder.Entity("server.Models.Historian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("TagNameId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_name");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_");

                    b.Property<decimal>("Value")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("value_");

                    b.HasKey("Id");

                    b.HasIndex("TagNameId");

                    b.ToTable("Historian", (string)null);
                });

            modelBuilder.Entity("server.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment");

                    b.Property<bool>("IsChangement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_changement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int?>("OfEnCoursId")
                        .HasColumnType("integer")
                        .HasColumnName("of_en_cours");

                    b.Property<int?>("OfSuivantId")
                        .HasColumnType("integer")
                        .HasColumnName("of_suivant");

                    b.Property<int>("TempsChangement")
                        .HasColumnType("integer")
                        .HasColumnName("temps_changement");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId")
                        .IsUnique()
                        .HasDatabaseName("lines_equipment_key");

                    b.HasIndex("OfEnCoursId");

                    b.HasIndex("OfSuivantId");

                    b.ToTable("Lines", (string)null);
                });

            modelBuilder.Entity("server.Models.Of", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Of_")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("of_");

                    b.Property<string>("Produit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("produit");

                    b.Property<int>("QteProduite")
                        .HasColumnType("integer")
                        .HasColumnName("qte_produite");

                    b.Property<int>("QteTotale")
                        .HasColumnType("integer")
                        .HasColumnName("qte_totale");

                    b.HasKey("Id");

                    b.ToTable("ofs", (string)null);
                });

            modelBuilder.Entity("server.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("server.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tag_name");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifiant");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Equipment_Tag", b =>
                {
                    b.HasOne("server.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("equipment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("equipment_tag_equipment_fkey");

                    b.HasOne("server.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_name")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("equipment_tag_tag_name_fkey");
                });

            modelBuilder.Entity("server.Models.Historian", b =>
                {
                    b.HasOne("server.Models.Tag", "TagNameNavigation")
                        .WithMany("Historians")
                        .HasForeignKey("TagNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("historian_tag_name_fkey");

                    b.Navigation("TagNameNavigation");
                });

            modelBuilder.Entity("server.Models.Line", b =>
                {
                    b.HasOne("server.Models.Equipment", "Equipment")
                        .WithOne("Line")
                        .HasForeignKey("server.Models.Line", "EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("lines_equipment_fkey");

                    b.HasOne("server.Models.Of", "OfEnCours")
                        .WithMany("LinesEnCours")
                        .HasForeignKey("OfEnCoursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("lines_of_en_cours_fkey");

                    b.HasOne("server.Models.Of", "OfSuivant")
                        .WithMany("LinesSuivant")
                        .HasForeignKey("OfSuivantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("lines_of_suivant_fkey");

                    b.Navigation("Equipment");

                    b.Navigation("OfEnCours");

                    b.Navigation("OfSuivant");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.HasOne("server.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("users_role_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("server.Models.Equipment", b =>
                {
                    b.Navigation("Line");
                });

            modelBuilder.Entity("server.Models.Of", b =>
                {
                    b.Navigation("LinesEnCours");

                    b.Navigation("LinesSuivant");
                });

            modelBuilder.Entity("server.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("server.Models.Tag", b =>
                {
                    b.Navigation("Historians");
                });
#pragma warning restore 612, 618
        }
    }
}
